### ISSUE TITLE
Combine NumCenter = 1 and NumCenter = 2 code

### ISSUE THREAD

**Issue by mtfishman** [ITensor/TDVP#1]
Hi Mingru,

Thanks a lot for the contribution, looks great so far.

One thing we should do is combine the codes for NumCenter=1 and NumCenter=2, since they are quite similar (in fact they only look different up to a few lines of code).

-Matt

**Comment by mingruyang** [comment]
Yes, we can change that. I just didn't want in every sweep they need to determine what is the NumCenter so I made them separate.

**Comment by mtfishman** [comment]
I think the cost of those if-statements are the least of our worries when time evolving MPSs :).

I pushed a partial reorganization of the code, I think we can compress it a bit more.

**Comment by mingruyang** [comment]
Yes. I think we need to modify the sweepnext function to get a uniform interface for different center sites so that we can compress the current code further.

**Comment by mtfishman** [comment]
That's a good idea, we can just add a "NumCenter" arg to `sweepnext`.

**Comment by mtfishman** [comment]
This is fixed in the latest version.
