### ISSUE TITLE
Need to add bond dimension increase scheme

### ISSUE THREAD

**Issue by mtfishman** [ITensor/TDVP#2]
With NumCenter=2, the sample code gives:

```
Maximum bond dimension of H is 5
Initial energy = -3.75000
Sweeps:
1  MaxDim=2000, MinDim=1, Cutoff=1.0E-10, Niter=10, Noise=0.0E+00
2  MaxDim=2000, MinDim=1, Cutoff=1.0E-10, Niter=10, Noise=0.0E+00
3  MaxDim=2000, MinDim=1, Cutoff=1.0E-10, Niter=10, Noise=0.0E+00
4  MaxDim=2000, MinDim=1, Cutoff=1.0E-10, Niter=10, Noise=0.0E+00
5  MaxDim=2000, MinDim=1, Cutoff=1.0E-10, Niter=10, Noise=0.0E+00

----------------------------------------TDVP---------------------------------------

    vN Entropy at center bond b=8 = 0.015896088398
    Eigs at center bond b=8: 0.9978 0.0022 
    Largest link dim during sweep 1/5 was 4
    Largest truncation error: 2.21953e-16
    Energy after sweep 1/5 is -4.428582280697
    Sweep 1/5 CPU time = 0.0648s (Wall time = 0.0703s)

    vN Entropy at center bond b=8 = 0.046117724972
    Eigs at center bond b=8: 0.9921 0.0079 
    Largest link dim during sweep 2/5 was 4
    Largest truncation error: 5.2646e-13
    Energy after sweep 2/5 is -4.967028421820
    Sweep 2/5 CPU time = 0.0902s (Wall time = 0.0904s)

    vN Entropy at center bond b=8 = 0.080229619359
    Eigs at center bond b=8: 0.9844 0.0156 
    Largest link dim during sweep 3/5 was 4
    Largest truncation error: 1.65219e-11
    Energy after sweep 3/5 is -5.381739346310
    Sweep 3/5 CPU time = 0.0918s (Wall time = 0.0920s)

    vN Entropy at center bond b=8 = 0.113841364404
    Eigs at center bond b=8: 0.9759 0.0241 
    Largest link dim during sweep 4/5 was 5
    Largest truncation error: 5.6404e-11
    Energy after sweep 4/5 is -5.696254529383
    Sweep 4/5 CPU time = 0.0897s (Wall time = 0.0900s)

    vN Entropy at center bond b=8 = 0.145128298293
    Eigs at center bond b=8: 0.9671 0.0329 
    Largest link dim during sweep 5/5 was 5
    Largest truncation error: 2.58468e-11
    Energy after sweep 5/5 is -5.933668280320
    Sweep 5/5 CPU time = 0.0906s (Wall time = 0.0908s)

Energy after imaginary time evolution = -5.9336682803

Using overlap = -5.9336682803
----------------------------------------Zaletel---------------------------------------
Maximum bond dimension of expH is 4
Maximum bond dimension at time 0.1 is 3 

Energy using overlap at time 0.1 is -4.4271435762
Maximum bond dimension at time 0.2 is 4 

Energy using overlap at time 0.2 is -4.9648758204
Maximum bond dimension at time 0.3 is 4 

Energy using overlap at time 0.3 is -5.3793796416
Maximum bond dimension at time 0.4 is 4 

Energy using overlap at time 0.4 is -5.6939709057
Maximum bond dimension at time 0.5 is 4 

Energy using overlap at time 0.5 is -5.9315817783
```

But with NumCenter=1 it gives:

```
----------------------------------------TDVP---------------------------------------

    vN Entropy at center bond b=8 = -0.000000000000
    Eigs at center bond b=8: 1.0000 
    Largest link dim during sweep 1/5 was 1
    Largest truncation error: 0
    Energy after sweep 1/5 is -3.750000000000
    Sweep 1/5 CPU time = 0.00545s (Wall time = 0.00549s)

    vN Entropy at center bond b=8 = -0.000000000000
    Eigs at center bond b=8: 1.0000 
    Largest link dim during sweep 2/5 was 1
    Largest truncation error: 0
    Energy after sweep 2/5 is -3.750000000000
    Sweep 2/5 CPU time = 0.00481s (Wall time = 0.00484s)

    vN Entropy at center bond b=8 = -0.000000000000
    Eigs at center bond b=8: 1.0000 
    Largest link dim during sweep 3/5 was 1
    Largest truncation error: 0
    Energy after sweep 3/5 is -3.750000000000
    Sweep 3/5 CPU time = 0.00370s (Wall time = 0.00373s)

    vN Entropy at center bond b=8 = -0.000000000000
    Eigs at center bond b=8: 1.0000 
    Largest link dim during sweep 4/5 was 1
    Largest truncation error: 0
    Energy after sweep 4/5 is -3.750000000000
    Sweep 4/5 CPU time = 0.00367s (Wall time = 0.00370s)

    vN Entropy at center bond b=8 = -0.000000000000
    Eigs at center bond b=8: 1.0000 
    Largest link dim during sweep 5/5 was 1
    Largest truncation error: 0
    Energy after sweep 5/5 is -3.750000000000
    Sweep 5/5 CPU time = 0.00366s (Wall time = 0.00369s)

Energy after imaginary time evolution = -3.7500000000

Using overlap = -3.7500000000
```

~~It looks like the MPS is not getting updated.~~

Edit: We need to implement a bond dimension increase scheme for 1-site TDVP.

**Comment by mingruyang** [comment]
Yes, that's the inherent problem with the 1-site algorithm, since it cannot increase the bond dimension after sweeps. If we want to use the 1-site algorithm, the bond dimension of the initial MPS should not be 1.

**Comment by mingruyang** [comment]
The projection error can also be large if we start from a product state using the 2-site algorithm. In page 68 of [https://arxiv.org/abs/1901.05824](url), they suggested a way to artificially increase the bond dimension of a product state.

So maybe a better sample code will not be an imaginary time evolution from a product state. But other kinds of evolution starting from a ground state with larger bond dimension...

**Comment by mtfishman** [comment]
Ah yes of course. We should include a scheme for bond dimension increase in the repo (whatever we find is best), so we can keep this as an open issue for that.

Alex Wietek (@alexwie) here at CCQ has been doing a lot of TDVP recently, and I believe he found that doing a few steps of TEBD has worked well to increase the bond dimension.

**Comment by mingruyang** [comment]
I added a bond dimension increasing scheme according to page 70 of https://arxiv.org/abs/1901.05824.

**Comment by emstoudenmire** [comment]
Good idea. At some point soon I want to provide some ‘code formula’ examples of TDVP on the ITensor website, and having a bond growth scheme is an important part. Really appreciate this contribution of TDVP overall!

**Comment by emstoudenmire** [comment]
Just as a comment, another scheme is to do a few steps of global Krylov. But we will need a good global Krylov code first; Alex Wietek at Flatiron has one so we will likely ask him to contribute it to ITensor.

One last scheme I was considering today is to make a random MPS basis, and project the desired starting state into it. However, this runs into a problem I still haven’t quite solved of how to make proper random MPS bases out of quantum-number conserving tensors. (It’s easy if one knows the layout of the virtual indices, but these are not so simple to determine a priori.)

**Comment by mingruyang** [comment]
I think the current appExp function in ITensor can be used to do global Krylov by just changing the inputs and .product function to applyMPO. I made a global Krylov function according to my previous appExp function. I can make a pull request if you want.

Actually I and Steve recently did some work on the subspace expansion of TDVP. I'm very interested in how well your random MPS basis will work. For determining the quantum number blocks, I think one can try to use the blocks in the MPS resulted from applying the Hamiltonian to the original MPS or even higher orders.
