### ISSUE TITLE
Energy and norm conservation

### ISSUE THREAD

**Issue by rborrelli** [ITensor/TDVP#4]
Hi all,
I am trying to use the TDVP code but I don't understand why in the sample run energy is not preserved during time evolution in both 1-site and 2-site algorithms.
Thanks,
Raffaele

**Comment by rborrelli** [comment]
Sorry, I didn't realize that the example was for imaginary time evolution.

**Comment by emstoudenmire** [comment]
No problem, but thanks very much for taking a careful look at this especially because it’s a new code! Let us know if you do find any issues.
