### ISSUE TITLE
1 center TDVP fails with LocalOp is null message

### ISSUE THREAD

**Issue by rborrelli** [ITensor/TDVP#5]
Hi, starting from version 3.1.2 of ITensor I cannot run the one-center TDVP anymore. It fails with the message "LocalOp is null" message. 

Raffaele

**Comment by emstoudenmire** [comment]
Hi Raffaele,
Thanks for catching this. It's actually not a bug with this repo (ITensor/TDVP) but was introduced accidentally with the latest update to ITensor/ITensor. I'll answer on the forum also, but could you please provide a minimal code to reproduce? Thanks -

**Comment by emstoudenmire** [comment]
Ok this should now be fixed by ITensor/ITensor#354. Please reopen this issue if it continues not to work!
